/// @desc Create the enum to reference the upgrade array index.

function CreateUpgradeEnum() {
	enum UPGRADE {
		PENCIL,
		MATHEMATICIAN,
		TRIGONOMETRY,
		AMPHETAMINE,
		ARTIFICIAL_INTELLIGENCE,
		QUANTUM_COMPUTING,
		SPACE_TRAVEL,
		TIME_TRAVEL,
		ANIMAL_SACRIFICE,
		UNDEAD_EXPERIMENTS,
		NUCLEAR_WAREFARE,
	}
}